name: Coverage

on:
  workflow_call:
    inputs:
      coverage:
        description: "Enable coverage"
        default: false
        type: boolean 
      python-version:
        description: "Set Python version"
        default: 3.11
        type: string
      language:
        description: "Set the language to be linted"
        type: string
        default: node 


jobs:    
  python-coverage:
    name: Python Coverage
    if: ${{ inputs.coverage && inputs.language == 'python' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
         
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }} 
          
      - name: Install dependencies      
        run: |
          python -m pip install --upgrade pip
          pip install tox
          
      - name: Run Ruff Linter
        id: run-tox
        run: |
          tox -e py
