name: Terraform Prepare

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string
        default: 1.8.3

jobs:
  terraform_prepare:
    name: Terraform Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: ${{ inputs.terraform_version }}
