name: Terraform Prepare

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string
        default: 1.8.3

jobs:
  terraform_prepare:
    name: Terraform Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0
          ref: "${{ github.head_ref || github.ref }}"    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: ${{ inputs.terraform_version }}
